name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Specify the version of Terraform to use

      # Step 3: Set AWS Credentials (from GitHub Secrets)
      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set AWS Access Key from GitHub Secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set AWS Secret Key from GitHub Secrets
          AWS_REGION: 'us-east-1'  # Set your AWS region (adjust accordingly)
        run: echo "AWS credentials are set."

      # Step 4: Clear Terraform Cache (for debugging)
      - name: Clear Terraform Cache
        run: |
          rm -rf ./infra/.terraform  # Clear any cached Terraform state

      # Step 5: Check Terraform Version (for debugging)
      - name: Check Terraform version
        run: terraform version
        working-directory: ./infra  # Ensure correct path to your `infra` folder

      # Step 6: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra  # Ensure correct path to your `infra` folder

      # Step 7: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra  # Ensure correct path to your `infra` folder

      # Step 8: Plan Terraform Changes
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra  # Ensure correct path to your `infra` folder

      # Step 9: Apply Terraform Changes (This step requires manual approval or conditional checks)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra  # Ensure correct path to your `infra` folder
        if: github.event_name == 'push'  # Only apply when directly pushing (not on PR)

      # Step 10: Upload Terraform State
      - name: Upload Terraform State
        uses: actions/upload-artifact@v2  # Use v2 instead of v3
        with:
          name: terraform-state
          path: ./infra/.terraform/terraform.tfstate  # Path to Terraform state file
