name: CI/CD Workflow with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Verify secrets (nice touch, keeping it)
      - name: Check AWS Secrets
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "❌ AWS_ACCESS_KEY_ID is missing!" && exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "❌ AWS_SECRET_ACCESS_KEY is missing!" && exit 1
          fi

      # Step 5: Initialize Terraform with backend config
      - name: Terraform Init
        run: terraform init -backend-config="region=us-east-1"

      # Step 6: Validate configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Show execution plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 8: Apply the plan if everything’s good
      - name: Terraform Apply
        env:
          META_GRAPH_API_ACCESS_TOKEN: ${{ secrets.META_GRAPH_API_ACCESS_TOKEN }}
        run: |
          terraform apply -auto-approve tfplan
